//
//  BlockerRulesMapper+Data.swift
//  MagicSecurity
//
//  Created by User on 1.05.25.
//

extension BlockerRulesMapper {
    static let gamblingDomains: [String] = """
        00000onlinecasino.com
        000333onlinecasino.com
        000777triplewin.com
        007sportsbetting.com
        00casino.com
        01-online-casino.com
        01casinos.com
        01poker.fr
        01turf.com
        0casino-online.com
        0casinoonline.com
        0internet-casino.com
        0virtual-casino.com
        1-blackjack.com
        1-casino-gambling-online.com
        1-online-casinos-guide.com
        1-poker-games-online.com
        100blackrhino.com
        100pour100-gratuit.com
        1010casino.com
        123-onlinecasino.com
        123gambling.com
        123onlinecasino.com
        1980-games.com
        1bet.com
        1jour1pari.com
        1luckygamblercasino.com
        1stnflpicks.com
        1stplacecasino.com
        200pour100.fr
        200pourcent.fr
        209.8.180.34.com
        20dollars2surf.com
        20dollarspass.com
        21grandcasino.net
        21onlinecasino.com
        21st-century-casino.com
        24kbets.com
        30top-casinos-france.net
        32red.com
        32vegas.com
        38-special-casino.com
        3bvideostar.fr
        3dgamers.com
        3gamers.com
        40casino.com
        49ercasino.com
        4cherrycasino.com
        4jokerscasino.com
        50starscasino.com
        576.hu
        5dimes.com
        6sixsix.com
        770.com
        7casinoonline.com
        888.com
        888.fr
        888casino.info
        8casinos.com
        91dapai.cn
        a-baccarat-casino.com
        a1vegas.com
        aaaonlinecasino.com
        abcgambling.com
        abetawaycasino.com
        aboutbingoonline.com
        absolu-casino.com
        absolucasino.com
        absoluflash.com
        absolutepoker.com
        absolutist.com
        abysscasino.com
        accasino.net
        accreditedcasinos.com
        acesclubcasino.com
        acesgoldcasino.com
        aceshighonlinecasino.com
        aceskasino.com
        acespalace.com
        achla-casino.com
        actioncitycasino.com
        actionsportscasino.com
        ad0.gamesweb.com
        adimg1.gamesweb.com
        admiralbet.com
        adonfff.com
        adventurecompanygames.com
        agagames.com
        agamblingcasino.com
        aimgames.com
        airportcasino.de
        akiracasino.com
        aladdinsgoldcasino.com
        alienvspredatormovie.com
        allbet.gr
        allgames.gamesh.com
        allmagic.ru
        allonlineslots.com
        allpokercasino.com
        allslotscasino.com
        allsportscasino2.com
        allstarslots.com
        alpencasino.com
        alpscasino.com
        amazinggamblingsystems.com
        ambercoastcasino.com
        ambrosine.com
        americanacasino.com
        amigasolitaire.free.fr
        anime-game-osts.com
        antiguagaming.com
        aom.heavengames.com
        apexsportsbook.com
        aquateencentral.com
        aqvacasino.com
        arcadeabyss.com
        arcadecasino.com
        argentdunetinfos.org
        argentmania.com
        argentsurlenet.com
        aroundthesims.com
        artgamer.com
        arushgames.com
        asiacasino.com
        asianalternative.com
        astuces-jeux.net
        atbforum.com
        athomesportsbook.com
        atlantis-evolution.tacgames.com
        avalanchecasino.com
        avatarcasino.com
        avdpoker.com
        avp-movie.com
        axelgame.free.fr
        axygames.com
        aztecgaming.com
        bamboocasino.com
        banalotto.fr
        bananalotto.fr
        bancoloto.com
        barakacasino.com
        barbarycoastcasino.com
        barre-de-surf.fr
        bekendenederlanders.nl
        bellavegas.com
        belmontcasino.com
        berrycherry.com
        best-gambling.biz
        best-pronostic.com
        bestcasinocomps.com
        bestcasinoguide.com
        bet-at-home.com
        bet2play.com
        bet365.com
        bet365.gr
        betandwin.com
        betandwin.de
        betcash.biz
        betcentral.com
        betclic-mobile.fr
        betclic.com
        betclic.fr
        betclick-mobile.fr
        betclick.com
        betclick.fr
        betclickmobile.fr
        betclicmobile.fr
        betdaq.co.uk
        betfair.com
        betfairgames.com
        betnet.fr
        betonsports.com
        betoto.com
        betoto.gr
        betshop.gr
        betsson.com
        betsson.se
        better-betting.com
        better.it
        betterwaycasinos.com
        bettheglobe.com
        betuscasino.com
        betuwincasino.com
        betway.com
        betwin-poker.com
        betzone.com
        big-ptp.fr
        bigapple-casino.com
        bigcatcasino.com
        bigredcasino.com
        bilyoner.com
        bingopalace.com
        black-jack-casino.com
        blackcatcasino.com
        blackcatscasino.com
        blackjack-gratuit.com
        blackjack-homepage.com
        blackjack-online.20m.com
        blackjackballroom.com
        blacktiecasino.com
        bluediamondcasino.com
        bluesq.com
        boathousecasino.com
        bodogcasino.com
        bodoglife.com
        bonus-jeu-casino.com
        bonus-jeux-casino-poker.com
        bonusaupoker.com
        bonuspluscasino.monsite.orange.fr
        bookmaker.com
        booksforgamblers.com
        booloto.com
        boutique-cadeaux.info-commerce.fr
        bowmanbet.com
        brightshare.com
        bubusurf.fr
        buckyscasino.com
        bwin.com
        bwin.com.ar
        bwin.fr
        bwin.org
        c0mment-gagner.org
        cabanacasino.com
        cachecasinolasvegas.com
        cacheeuro-casinos.net
        cachewww.cpays.com
        cachewww.prestigecasino.com
        cadeaux-poker.com
        cadillacjacksresort.com
        cadomagic.com
        californiacasino.com
        cameocasino-fr.com
        campuspokermasters.com
        captaincookscasino.com
        carbonpoker.com
        caribbeannightscasino.com
        caribbeanstarcasino.com
        caribbeanstudpokerrule.com
        caribbeansunpoker.com
        caribbeantreasurecasino.com
        carribbeanpoker.co.uk
        cashbreak.com
        cashcitycasino.com
        cashclic.fr
        cashmonsterscasino.com
        cashpot.fr
        casino-4fun.com
        casino-aladdin-web.com
        casino-and-casinos.com
        casino-atlantis.com
        casino-broceliande.com
        casino-choice.com
        casino-club.com
        casino-en-ligne.fr.vu
        casino-fr-online.info
        casino-games-free.com
        casino-gaming.com
        casino-golden-poker.be
        casino-in-linea.it.st
        casino-internet.info
        casino-jeux-argent.fr
        casino-kassel.de
        casino-online-on-line.com
        casino-pariswin.com
        casino-partouche.com
        casino-poker.ch
        casino-rentable.com
        casino-searcher.com
        casino-sh.de
        casino-slot.net
        casino-sportsbetting-directory.com
        casino-star.info
        casino-titanic.com
        casino-tropez-fr.com
        casino-world.co.uk
        casino.co.uk
        casino.com
        casino.free-money.co.uk
        casino.plein.nl
        casino2007.biz
        casino21.com
        casino4turks.com
        casino770.com
        casinoadvertising.org
        casinoalitalia.com
        casinoasian.com
        casinoaustralia.com
        casinoavalanche.com
        casinobeauty.com
        casinobellini.com
        casinoblue.com
        casinobluestar.com
        casinobonusguy.com
        casinobonusplus.topbonplan.fr
        casinocamelot.com
        casinocareers.com
        casinocaribe.com
        casinocasinocasino.site.voila.fr
        casinochique.com
        casinocity.com
        casinoclassic.com
        casinocoins.com
        casinocorp.com
        casinocorpsportsbook.com
        casinocounty.com
        casinodelasvegas.com
        casinodelrio-fr.com
        casinodelrio.com
        casinodinero.com
        casinoebet.com
        casinoelegante.com
        casinoeu.com
        casinoeuro.com
        casinoexperience.com
        casinoextreme.com
        casinofashion.com
        casinofreebonus.com
        casinogambler.net
        casinogambling.about.com
        casinogamblingfun.com
        casinogane.com
        casinogane.net
        casinogold.com
        casinogoldenriviera.com
        casinogoldvip.com
        casinograndbay.com
        casinograndprix.com
        casinogratuitenligne.net
        casinohunt.com
        casinoinc.com
        casinoinform.freehomepage.com
        casinoinn.com
        casinoitalian.com
        casinokats.com
        casinoking.com
        casinolasvegas-online.com
        casinolasvegas.com
        casinolatinos.com
        casinolifemagazine.com
        casinolove.com
        casinoluck.com
        casinolux.com
        casinoluxor.com
        casinomatic.com
        casinonational.com
        casinoofthekings.com
        casinoonnet.com
        casinoorient.com
        casinopacific.com
        casinopartouche.org
        casinopicnic.com
        casinoplanete.com
        casinoplayer.com
        casinoplayersadvocate.com
        casinoplaza.com
        casinoposeidon.com
        casinoprestige.co.uk
        casinopromote.com
        casinopromotion.com
        casinoriva.com
        casinorivernile.com
        casinos-hits.com
        casinos-jackpots.net
        casinos-neteller.com
        casinos.9-online.com
        casinos.stills.com
        casinos2go.com
        casinosandco.com
        casinoscout.com
        casinosenlaweb.com
        casinosflash.com
        casinosforfun.com
        casinoshare.eu
        casinoslotmachine.org
        casinoslotmachinegames.com
        casinosoft.com
        casinosonlinecasinos.org
        casinospielen.de
        casinosplendido.com
        casinosur.com
        casinotechnieken.nl
        casinotokyo.com
        casinotop10.net
        casinotreasure.com
        casinotropez.com
        casinotrust.com
        casinouniverse.com
        casinoutopia.com
        casinovations.com
        casinovegasusa.com
        casinovirtuel.net
        casinoweb.org
        casinoxl.nl
        casion-casino.com
        cassava.net
        casualpoker.com
        ccasino.com
        cdpoker.com
        cdpoker.fr
        celllottery.com
        centrebet.com
        champagnecasino.com
        charlotteaupoker.com
        chat.orion.de
        chatter.uol.com.br
        cheatland.com
        cherrycasino.com
        cherryredcasino.com
        chilipari.fr
        chilipoker.com
        cleopatras-casino.com
        cleopatraspalacecasino.com
        club-de-poker.fr
        club8casino.com
        club8casino.net
        clubchance.com
        clubmardigrascasino.com
        clubpoker.net
        clubriocasino.com
        clubvipcasino.com
        cncrenegade.com
        cocoricode.com
        codecasino.com
        codeland.fr
        codeotop.com
        codes-gratis.com
        codeskado.com
        comment-gagne.org
        commentgagner.org
        competitivechallenge.com
        coralpoker.com
        cotedazurpalace.com
        coupedumonde-pari.fr
        cowboycasino.net
        craps.com
        crazyslots.com
        crocastuce.fr
        cyberbetcasino.com
        cybersportsbet.com
        datdrop.com
        defeatthecasinos.com
        demo-jeux-casino.mondo-casinos.com
        desdelasvegas.com
        devenir-gangster.com
        diamondclubcasino.com
        directlinecasino.com
        distribucodes.com
        doubledowncasino.com
        download-slotmachines.com
        doylesroom.com
        dragoncasino.com
        dumbcasinowomen.com
        dutchtalk.com
        e-casino.tv
        e-lottery-syndicat-mondial.fr.nr
        e777.net
        easybets.com
        easyrollerscasino.com
        egyptiangoldcasino.com
        ellis-island-online-casino.com
        elsanjuancasino.com
        empirepoker.com
        enfer-des-codes.net
        eurobarre.com
        eurogrand.com
        eurojeux.hbg.fr
        europaacasino.com
        europacasino-fr.com
        europacasino.com
        european-poker.com
        europoker.com
        eurosportbet.fr
        eurovore.com
        everestpoker.com
        everestpoker.fr
        everestpoker.net
        eworldcasino.com
        excelsiorcasino.com
        exoticslotscasino.com
        expekt.com
        ez-lotto.com
        ezmoneycasino.com
        eznetcasino.com
        fairplaycasino.com
        fairpoker.com
        fashioncasino.com
        favoritecasinos.com
        fcasino.net
        fdj.directinet.fr
        fdj.fr
        fdjeux.net
        femalegamblers.org
        fiestacasino.com
        findgambling.us
        firstbet.fr
        firstwebcasino.com
        flashvegas.com
        flopturnriver.com
        football-dimension.com
        football-pari.fr
        football365.fr
        fortunelounge.com
        forum.cf-poker.com
        forumdujoueur.com
        foxtee.com
        foxwoods.com
        fr.bananalotto.com
        fr1.bananalotto.com
        france-abonnements.fr
        france-pari.fr
        fre-free-games.com
        free-casino-game.org
        free-gambling-online.com
        free-picks.com
        free-poker.jwtl.com
        free.jeux-poker-casino.com
        freecasinocash.4t.com
        freecasinomoney4u.com
        freelotto.com
        freeonline-casinos.net
        freesb.com
        freeslot.com
        french.eurokingclub.com
        friendbet.fr
        fulltiltpoker.com
        fulltiltpoker.fr
        funmagicjackpot.com
        furby.com
        gagnerpartager.fr
        gagnez-argent.org
        galabackgammon.org
        galacasino.co.uk
        galaxiworld.com
        gambleonline.org
        gamblepicks.com
        gamblerplace.com
        gamblerplanet.com
        gamblersguideonline.com
        gamblersuniverse.com
        gamblersworld.com
        gamblerszoo.com
        gamblesite.com
        gamblestreet.com
        gambletribune.org
        gambleup.com
        gambling-affiliation.com
        gambling-directory.tv
        gambling-gazette.com
        gambling-strategy.net
        gambling-tips.net
        gambling-tutorial.com
        gambling.com
        gambling.nl
        gamblingcity.net
        gamblingfaq.net
        gamblinglinks.com
        gamblinglinks.net
        gamblingplanet.org
        gamblingsoftware.com
        gamblingtimes.com
        gamebookers.fr
        games.co.uk
        gametimecasino.com
        gametips.nl
        gamingandcasinofund.com
        gamingclub.com
        gangsta-poker.com
        geishalounge.com
        gemcasino.com
        genybet.fr
        go4millionscasino.com
        gocasino.com
        gokjewagen.nl
        goldclubcasino.com
        goldcoastcasino.com
        goldencoastcasino.com
        goldengambler.com
        goldenjeux.net
        goldenpalacenv.com
        goldenpalacepoker.com
        goldenreefcasino.com
        goldenrivieracasino.com
        goldenrivierapoker.com
        goldentigercasino.com
        goldminecasino.com
        goldstarcasino.com
        goldstrikecasino.com
        gonegambling.com
        grandcentralcasinos.com
        grandhotelcasino.com
        grandjeu-cdiscount-casino.com
        grandmondial.com
        grandscasinos.com
        grandviewproducts.com
        gratisgokkasten.nl
        gratispokergeld.nl
        grattage.com
        greatwaygambling.net
        grosvenorcasinos.com
        guide-casino.com
        gurutracker.com
        harrahs.com
        hawaiiancasino.com
        highrollercasino.com
        hipodromosanisidro.com
        hold-em-poker.com
        hold-em-poker.eu
        holdemweb.com
        holdemweb.net
        homepokertourney.com
        hooliganweb.com
        hotluckgambling.net
        how-to-cheat-the-casinos.com
        ibetcasino.com
        ilovebacon.com
        imperialcasino.com
        imperialpoker.com
        indexbetting.net
        infobarre.perso.sfr.fr
        infos-casino.com
        instacashcasino.com
        instantcashcasino.com
        interbetcasino.com
        intercasino.com
        intercasinopoker.com
        internetcasinosgambling.com
        internetgambler.com
        internetvirtualcasino.com
        interpoker.com
        interwetten.com
        intralot.fr
        intralotpari.fr
        iogaffiliate.com
        iwon.com
        jackpotcity.com
        jackpotplus.com
        jackpotsinaflash.com
        jacksorbettervideopoker.com
        jajio.com
        jamaicabaycasino.com
        jeu-casino.net
        jeu-casino.showbizmusic.com
        jeudecasino.com
        jeudecasino.org
        jeudepoker.org
        jeudepokergratuit.org
        jeudunet.com
        jeux-casino-gratuit.com
        jeux-casino-gratuits.com
        pokernet.com
        pokernetonline.com
        pokernews.com
        pokernonstop.ru
        pokerpage.biz
        pokerpartnership.com
        pokerparty.com
        pokerportal.sc
        pokersavvy.com
        pokersite.com
        pokersites.com
        pokerstars.com
        pokerstars.fr
        pokerstars.net
        pokersubito.fr
        pokersupplies.com
        pokertube.com
        pokeruitleg.info
        pokerupdates.com
        pokerworks.com
        pokerworld.com
        pokerxtrem.fr
        premiercasinoevents.com
        primecasino.com
        princemonacocasino.com
        privatecasino.com
        pronosoft.com
        ptc.creadunet.com
        purevegascasino.com
        racingcasino.com
        rapido-casinos.com
        """
        .components(separatedBy: "\n")
}
